<?php

namespace Ens\JobeetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository
{
    public function getLatestJobs()
    {
      $qb = $this->getEntityManager()->createQuery('SELECT j FROM EnsJobeetBundle:Job j WHERE j.expires_at > :date')
            ->setParameter('date', date('Y-m-d H:i:s', time() - 86400 * 30));
        return $qb->getResult();
    }
}